version: '2'
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./server_config/nginx/reverse_proxy_config_dev:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/letsencrypt:/var/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    links:
      - web
    depends_on:
      - web
    volumes_from:
      - web
  web:
    restart: always
    build: .
    environment:
      - "NODE_ENV=production"    
    command: node app.js --prod
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules